<?php

/**
 * @file
 * Add scripts from the frontend on all over the site.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cookieyes_scripts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cookieyes_scripts':
      $output = '<h2>' . t('About') . '</h2>';
      $output .= '<p>' . t('This module allows you to add CookieYes scripts in your site or , You do not need to open any file for this purpose.') . '</p>';
      $output .= '<h2>' . t('Uses') . '</h2>';
      $output .= '<p>' . t('CookieYes GDPR Consent provides you the capability to quickly add the scripts in your site. You can configure them from the Administer -> Configuration -> Development -> CookieYes GDPR Consent') . '</p>';

      return $output;
  }
}

/**
 * Implements hook_page_top().
 *
 * Add scripts after the body tag on overall the site which are defined on the settings page.
 */
function cookieyes_scripts_page_top(array &$page_top) {

  $body_section = \Drupal::config('cookieyes_scripts.body.settings')->get();

  // Do not render if not enabled

  if(empty($body_section['enable'])){
      return;
  }
  
  // Do not render  for admin screens

  $admin_context = \Drupal::service('router.admin_context');
  if ($admin_context->isAdminRoute()) {

     return;
  }

  if (isset($body_section['scripts']) && !empty($body_section['scripts'])) {
    $output_scripts = preg_split("/(<\/script>|<\/noscript>)/", $body_section['scripts']);
    $i = 1;
    foreach ($output_scripts as $row) {

      if (empty($row)) {
        continue;
      }

      $script_tag  = 'script';
      $script_attr = [];
      $value       = '';

      $script_attributes = preg_replace('/(<script|<noscript)/', '', $row, 1);
      $get_script_attr   = preg_split('/(>)/', $script_attributes, 2);

      if (isset($get_script_attr[1])) {
        $value = $get_script_attr[1];
      }

      $get_script_tag = preg_split('/<noscript/', $row, 2);

      if (isset($get_script_tag[1])) {
        $script_tag = 'noscript';
      }

      if (isset($get_script_attr[0]) && !empty($get_script_attr[0])) {
        $get_attr   = preg_replace('/(\'|\")/', '', $get_script_attr[0]);
        $get_attr   = preg_replace('/\s+/', ',', $get_attr);
        $get_attr   = preg_replace('/(,=,|,=|=,)/', '=', $get_attr);
        $fetch_attr = explode(',', $get_attr);

        foreach ($fetch_attr as $attr) {
          if (empty($attr)) {
            continue;
          }

          $attr_key_value = explode('=', $attr);
          if (2 <= count($attr_key_value)) {
            $script_attr[$attr_key_value[0]] = preg_replace('/' . $attr_key_value[0] . '=/', '', $attr, 1);
          }
          else {
            $script_attr[$attr_key_value[0]] = $attr_key_value[0];
          }
        }
      }

      $page_top['top_scripts_' . $i] = [
        '#type'  => 'html_tag',
        '#tag'   => $script_tag,
        '#value' => $value,
      ];
      if (!empty($script_attr)) {
        $page_top['top_scripts_' . $i]['#attributes'] = $script_attr;
      }
      $i++;
    }
  }
}

