augmentor.settings:
  type: config_object
  label: 'Augmentor settings'
  mapping:
    augmentors:
      type: sequence
      label: 'Augmentors'
      sequence:
        type: mapping
        mapping:
          name:
            type: string
          label:
            type: string
          weight:
            type: integer
